kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.app.release_label }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.release_label }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        # Immutable
        app: {{ .Values.app.release_label }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: web2-container
          image: {{ .Values.current_image.repository }}:{{ .Values.current_image.tag }}
#          envFrom:
#            - configMapRef
#                name: env-conf
          env:
            - name: URL1
              valueFrom:
                configMapKeyRef:
                  name: env-conf
                  key: KEYS
#          env:
#            - name: URL1
#              valueFrom:
#                configMapKeyRef:
#                  name: env-conf
#                  key: URL1
#            - name: URL2
#              valueFrom:
#                configMapKeyRef:
#                  name: env-conf
#                  key: URL2
          volumeMounts:
            - name: config-nginx
              mountPath: /etc/nginx
              readOnly: true
            - name: config-www
              mountPath: /var/www
              readOnly: true
          ports:
            - containerPort: 80
              name: web2-nginx-port
{{- if eq $.Values.limits.enabled true}}
          resources:
            limits:
              memory: {{ $.Values.limits.memory }}
              cpu: {{ $.Values.limits.cpu }}
{{- end}}
      volumes:
        - name: config-nginx
          configMap:
            name: web2-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: config-www
          configMap:
            name: web2-www-index
            items:
              - key: index.html
                path: index.html

