kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.release_label }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    nodePort: 30002
    port: 9180
    targetPort: web2-nginx-port
