---
kind: Service
apiVersion: v1
metadata:
  name: custom-service-grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    nodePort: 30000 # any port 30000-32767 that will be open on the node
    port: 8888
    targetPort: grafana # name of container port 3000

